# fly.toml app configuration file generated for streamline-bank on 2025-07-06T04:50:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'streamline-bank'
primary_region = 'cdg'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '1641'

[http_service]
  internal_port = 1641
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
